### PR TITLE
Locale for new location and activity title states

### PR DESCRIPTION
**Pull request by niklasva82**
zetkin/zetkin-common#57 required for this

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
It seems to me like this PR does not update the submodule reference for `src/common`. Is that right?

**Review by richardolsson — APPROVED** [review]
All good!

**Comment by richardolsson** [comment]
Oh no, there's a merge conflict now. Can you have a look @niklasva82?

**Comment by niklasva82** [comment]
Merged master and everything works!

**Review by richardolsson — APPROVED** [review]
Perfect! Thanks. 💯

**Pull request merged**
