### PR TITLE
Migrate to lefalet maps

### PR DESCRIPTION
**Pull request by niklasva82**
Migrate call interface to Leaflet maps

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
I believe you forgot this map? It will need to be either updated to a dynamic map (but perhaps with interaction disabled?) or just fully disabled.

Call will exist for a long time, so ideally we don't disable it, unless we feel that it's an unnecessary feature.


image

**Comment by niklasva82** [comment]
Added a static map that queries Nominatim/OSM to get coordinates from address.
image

**Comment by niklasva82** [comment]
I discovered that one issue with using Nominatim is that the acceptable use specifies a max of 1 request per second, which applies per website/application. This could cause problems during major campaigns.

**Review by richardolsson — APPROVED** [review]
This looks good to me. As long as it's the right version of common (you decide what's right) I think this can be merged as is. Otherwise, push an update to the common ref and I will approve anew.

**Comment by richardolsson** [comment]
Oh, you pushed while I was reviewing, so I'm guessing this is good to merge now. I'll let you decide and do it, @niklasva82. 😊

**Comment by niklasva82** [comment]
Ah it appears I can't merge.
image

**Pull request merged**
